apiVersion: v1
data:
  jws-kubeconfig-abcdef: eyJhbGciOiJIUzI1NiIsImtpZCI6ImFiY2RlZiJ9..n_6QH4xGcEmq4rYnF66JBQuEWaZYVg8ef-L4WZT1qyU
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJT2swTmwwSjdtV2d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qa3hOelUwTWpkYUZ3MHpOakExTWpZeE56VTVNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNZaGYyZlRjKzJkYzlScjJyME9mM1ptZk11R3Y0QzZvSjRZUWpPTVlvc3dpZ0haT0x5Qzd2R1hzVHAKeWlNTmxESmhsMUVaazI4LytpRGFhbDNTZk96OTViaGZzTlYvL2ZldjY4c0hnajB1Vk5CRWk1UTcyTnIwVlJLcwpBU1M4eVRQWDRkYWh4R2liTTNxNFdqTlVIbzY4cnU2bmxNVzRPRkQ4Nkhkb3ZSMVdzZHhkNk13S0oxWkpLcmJoCnNlSzVmQUNaSGMwRmNLWkxBL0krZzEvL2ZNTVRET1c5dksyM1FzaU1mOGVubWtWMTBBRVAwWmkxM1BlL2Z3TVQKVFNlRHdMc2FaREp3REt3cXF5RkhmREpRdXMvNktFc0VxQUVvZE9TdmRtQTZobXZsWXpna3gxVGpiRjdkcWVwLwpsRFF3UzNyVVoxTy9PRDBwUGlIL0ZDUTMyNU5qQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUbE9jaHVpZUg0TURjbjRCQWVLU2dzZ0VGWDFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlBOTFp5c21jNwpMSndKcmNnbjNMNFFZTTVwbFlkTHdCOElyS0F1MjNWeWR1SVM2cU9Sd1FpdG5hS2NPazNxanp0YVNDSlhqaE95Ck1MSXZodkh1YVVlK0VkTnRhcnc0ako1Z0w3Y2trWnVWVW1NKzlxRXJBTVNnZlFrVkp3bDRmeU4vNDY2VFRmYlMKSXV0czY5Mk96a3JKNjBuMnBTWGhDNStxMm5sckgxZFFoei84OEh6VUZrcWVNZCtsOHQ5bmpKZWJQQyszanZtMgp6bmpqbWkwWW1idlRPS1BkTGxPZW9Qb3k1clZMNzAwSUpMRWxZRDh5anIva1dDM2ptemk2UjlqSm82WlAyckloCjR2Yy8xYTFyY0tlMnFCOFJkRHlQK3JIMzAzOTkzSlNNUHZFTE55L1RPYjNCZlpTYUpiRWY2eVczY1h1M01JUXMKM1VoUTRPejM3ayt3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://kind-control-plane:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    users: null
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
