#
# TODO 
# Add step to lint code and Dockerfile
# https://github.com/marketplace/actions/docker-lint
# https://github.com/MIS-Team24/khoyout-backend/blob/main/.github/workflows/main.yml
# Add step to build the Docker image.
#
name: CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: dockerfile
