name: CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dockerfilelint
      run: npm install -g dockerfilelint

    - name: Lint Dockerfile
      run: dockerfilelint .



    - name: Build Docker image
      run: docker build -t your-image-name .
