name: CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dockerfilelint
      run: npm install -g dockerfilelint

    - name: Install pylint
      run: pip install pylint

    - name: python lint
      run: pylint main.py
      continue-on-error: true

    - name: Run unit tests
      run: |
        pip install pytest pytest-asyncio aiohttp
        pytest
      continue-on-error: true


    - name: Build and push Docker image
      run: |
        docker build -t ezzops/senseapi-devopsproject:${{ github.sha }} .
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ezzops --password-stdin
        docker push ezzops/senseapi-devopsproject:${{ github.sha }}


    - name: Lint Dockerfile
      run: dockerfilelint dockerfile
      continue-on-error: true

