name: CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dockerfilelint
      run: npm install -g dockerfilelint



    - name: Python linting with flake8
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: flake8

    - name: Build and push Docker image
      run: |
        docker build -t senseAPI-DevOpsProject:${{ github.sha }} .
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ezzops --password-stdin
        docker push senseAPI-DevOpsProject:${{ github.sha }}


    - name: Lint Dockerfile
      run: dockerfilelint dockerfile

